In [1]:
import pandas as pd

In [4]:
states = pd.read_csv("uscounties_clustered.csv")

In [5]:
states.head()

,County,County Ascii,County Full,Point,State Id,State Name,Cluster,County Fips,F1,Lat,Lng,Population,Starting Dist
0,North Slope,North Slope,North Slope Borough,"(69.3122, -153.481)",AK,Alaska,0,2185,0,69.3122,-153.4810,10865,367.034339
1,Northwest Arctic,Northwest Arctic,Northwest Arctic Borough,"(67.053, -159.721)",AK,Alaska,0,2188,1,67.0530,-159.7210,7776,383.614163
2,Nome,Nome,Nome Census Area,"(64.9111, -164.0272)",AK,Alaska,0,2180,2,64.9111,-164.0272,10070,491.101230
3,Yukon-Koyukuk,Yukon-Koyukuk,Yukon-Koyukuk Census Area,"(65.5087, -151.3896)",AK,Alaska,0,2290,3,65.5087,-151.3896,5433,595.791658
4,Kusilvak,Kusilvak,Kusilvak Census Area,"(62.155, -163.3826)",AK,Alaska,0,2158,4,62.1550,-163.3826,8354,682.909427

In [8]:
states.groupby('Cluster')['Population'].sum().describe()

count    6.900000e+01
mean     4.778630e+06
std      7.173506e+05
min      4.112237e+06
25%      4.441432e+06
50%      4.587937e+06
75%      4.907534e+06
max      1.001964e+07
Name: Population, dtype: float64

In [16]:
states['Democrat'] = 0
states['Republican'] = 0
states['Other'] = 0
states.head()

,County,County Ascii,County Full,Point,State Id,State Name,Cluster,County Fips,F1,Lat,Lng,Population,Starting Dist,Democrat,Republican,Other
0,North Slope,North Slope,North Slope Borough,"(69.3122, -153.481)",AK,Alaska,0,2185,0,69.3122,-153.4810,10865,367.034339,0,0,0
1,Northwest Arctic,Northwest Arctic,Northwest Arctic Borough,"(67.053, -159.721)",AK,Alaska,0,2188,1,67.0530,-159.7210,7776,383.614163,0,0,0
2,Nome,Nome,Nome Census Area,"(64.9111, -164.0272)",AK,Alaska,0,2180,2,64.9111,-164.0272,10070,491.101230,0,0,0
3,Yukon-Koyukuk,Yukon-Koyukuk,Yukon-Koyukuk Census Area,"(65.5087, -151.3896)",AK,Alaska,0,2290,3,65.5087,-151.3896,5433,595.791658,0,0,0
4,Kusilvak,Kusilvak,Kusilvak Census Area,"(62.155, -163.3826)",AK,Alaska,0,2158,4,62.1550,-163.3826,8354,682.909427,0,0,0

In [11]:
votes = pd.read_csv("countypres_2000-2020.csv")

In [12]:
votes.head()

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,AL GORE,DEMOCRAT,4942,17208,20220315,TOTAL
1,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,11993,17208,20220315,TOTAL
2,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,RALPH NADER,GREEN,160,17208,20220315,TOTAL
3,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,OTHER,OTHER,113,17208,20220315,TOTAL
4,2000,ALABAMA,AL,BALDWIN,1003.0,US PRESIDENT,AL GORE,DEMOCRAT,13997,56480,20220315,TOTAL

In [13]:
votes_2020 = votes.loc[votes['year']==2020].copy()
votes_2020.head()

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
50524,2020,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,7503,27770,20220315,TOTAL
50525,2020,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,OTHER,OTHER,429,27770,20220315,TOTAL
50526,2020,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,19838,27770,20220315,TOTAL
50527,2020,ALABAMA,AL,BALDWIN,1003.0,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,24578,109679,20220315,TOTAL
50528,2020,ALABAMA,AL,BALDWIN,1003.0,US PRESIDENT,OTHER,OTHER,1557,109679,20220315,TOTAL

In [23]:
votes_2020[votes_2020['county_fips'].isnull()]

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
53317,2020,DISTRICT OF COLUMBIA,DC,DISTRICT OF COLUMBIA,NaN,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,317323,344356,20220315,TOTAL
53318,2020,DISTRICT OF COLUMBIA,DC,DISTRICT OF COLUMBIA,NaN,US PRESIDENT,OTHER,GREEN,1726,344356,20220315,TOTAL
53319,2020,DISTRICT OF COLUMBIA,DC,DISTRICT OF COLUMBIA,NaN,US PRESIDENT,JO JORGENSEN,LIBERTARIAN,2036,344356,20220315,TOTAL
53320,2020,DISTRICT OF COLUMBIA,DC,DISTRICT OF COLUMBIA,NaN,US PRESIDENT,OTHER,OTHER,4685,344356,20220315,TOTAL
53321,2020,DISTRICT OF COLUMBIA,DC,DISTRICT OF COLUMBIA,NaN,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,18586,344356,20220315,TOTAL
63983,2020,RHODE ISLAND,RI,FEDERAL PRECINCT,NaN,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,1276,1374,20220315,TOTAL
63984,2020,RHODE ISLAND,RI,FEDERAL PRECINCT,NaN,US PRESIDENT,JO JORGENSEN,LIBERTARIAN,6,1374,20220315,TOTAL
63985,2020,RHODE ISLAND,RI,FEDERAL PRECINCT,NaN,US PRESIDENT,OTHER,OTHER,7,1374,20220315,TOTAL
63986,2020,RHODE ISLAND,RI,FEDERAL PRECINCT,NaN,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,85,1374,20220315,TOTAL

In [31]:
votes_2020.loc[votes_2020['county_name']=="DISTRICT OF COLUMBIA", "county_fips"] = 11001
votes_2020.dropna(subset=["county_fips"], inplace=True)
votes_2020[votes_2020['county_fips'].isnull()]

Empty DataFrame
Columns: [year, state, state_po, county_name, county_fips, office, candidate, party, candidatevotes, totalvotes, version, mode]
Index: []

In [32]:
votes_2020['county_fips'] = votes_2020['county_fips'].astype('int')

In [33]:
votes_2020.head()

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
50524,2020,ALABAMA,AL,AUTAUGA,1001,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,7503,27770,20220315,TOTAL
50525,2020,ALABAMA,AL,AUTAUGA,1001,US PRESIDENT,OTHER,OTHER,429,27770,20220315,TOTAL
50526,2020,ALABAMA,AL,AUTAUGA,1001,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,19838,27770,20220315,TOTAL
50527,2020,ALABAMA,AL,BALDWIN,1003,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,24578,109679,20220315,TOTAL
50528,2020,ALABAMA,AL,BALDWIN,1003,US PRESIDENT,OTHER,OTHER,1557,109679,20220315,TOTAL

In [15]:
votes_2020['candidate'].unique()

array(['JOSEPH R BIDEN JR', 'OTHER', 'DONALD J TRUMP', 'JO JORGENSEN'],
      dtype=object)

In [48]:
votes_2020.loc[~votes_2020['party'].isin(["DEMOCRAT", "REPUBLICAN"]), 'candidatevotes']

2994050

In [56]:
for fip in states['County Fips']:
    fip_votes = votes_2020.loc[votes_2020['county_fips']==fip]
    states.loc[states['County Fips']==fip, 'Democrat'] = fip_votes.loc[fip_votes['party']=="DEMOCRAT", 'candidatevotes'].sum()
    states.loc[states['County Fips']==fip, 'Republican'] = fip_votes.loc[fip_votes['party']=="REPUBLICAN", 'candidatevotes'].sum()
    states.loc[states['County Fips']==fip, 'Other'] = fip_votes.loc[~fip_votes['party'].isin(["DEMOCRAT", "REPUBLICAN"]), 'candidatevotes'].sum()

In [60]:
states['total_votes'] = states['Democrat'] + states['Republican'] + states['Other']
states.tail()

,County,County Ascii,County Full,Point,State Id,State Name,Cluster,County Fips,F1,Lat,Lng,Population,Starting Dist,Democrat,Republican,Other,total_votes
3138,Putnam,Putnam,Putnam County,"(38.5086, -81.909)",WV,West Virginia,44,54079,1974,38.5086,-81.9090,57385,3626.465952,7878.0,20034.0,589,28501.0
3139,Raleigh,Raleigh,Raleigh County,"(37.7714, -81.2487)",WV,West Virginia,44,54081,2186,37.7714,-81.2487,74929,3687.312016,7982.0,24673.0,451,33106.0
3140,Roane,Roane,Roane County,"(38.714, -81.3483)",WV,West Virginia,44,54087,1963,38.7140,-81.3483,14129,3625.335915,1455.0,4213.0,95,5763.0
3141,Summers,Summers,Summers County,"(37.6559, -80.8586)",WV,West Virginia,44,54089,2235,37.6559,-80.8586,12125,3702.934630,1448.0,4074.0,63,5585.0
3142,Wyoming,Wyoming,Wyoming County,"(37.6096, -81.5492)",WV,West Virginia,44,54109,2196,37.6096,-81.5492,21581,3691.214551,1157.0,7353.0,82,8592.0

In [61]:
states[states['total_votes']==0]

,County,County Ascii,County Full,Point,State Id,State Name,Cluster,County Fips,F1,Lat,Lng,Population,Starting Dist,Democrat,Republican,Other,total_votes
0,North Slope,North Slope,North Slope Borough,"(69.3122, -153.481)",AK,Alaska,0,2185,0,69.3122,-153.4810,10865,367.034339,0.0,0.0,0,0.0
1,Northwest Arctic,Northwest Arctic,Northwest Arctic Borough,"(67.053, -159.721)",AK,Alaska,0,2188,1,67.0530,-159.7210,7776,383.614163,0.0,0.0,0,0.0
2,Nome,Nome,Nome Census Area,"(64.9111, -164.0272)",AK,Alaska,0,2180,2,64.9111,-164.0272,10070,491.101230,0.0,0.0,0,0.0
3,Yukon-Koyukuk,Yukon-Koyukuk,Yukon-Koyukuk Census Area,"(65.5087, -151.3896)",AK,Alaska,0,2290,3,65.5087,-151.3896,5433,595.791658,0.0,0.0,0,0.0
4,Kusilvak,Kusilvak,Kusilvak Census Area,"(62.155, -163.3826)",AK,Alaska,0,2158,4,62.1550,-163.3826,8354,682.909427,0.0,0.0,0,0.0
5,Fairbanks North Star,Fairbanks North Star,Fairbanks North Star Borough,"(64.8078, -146.5654)",AK,Alaska,0,2090,5,64.8078,-146.5654,97149,718.832600,0.0,0.0,0,0.0
6,Denali,Denali,Denali Borough,"(63.6714, -150.0118)",AK,Alaska,0,2068,6,63.6714,-150.0118,2187,724.868057,0.0,0.0,0,0.0
7,Bethel,Bethel,Bethel Census Area,"(60.9132, -159.8186)",AK,Alaska,0,2050,7,60.9132,-159.8186,18514,787.858663,0.0,0.0,0,0.0
8,Matanuska-Susitna,Matanuska-Susitna,Matanuska-Susitna Borough,"(62.3155, -149.5728)",AK,Alaska,0,2170,8,62.3155,-149.5728,106807,813.441667,0.0,0.0,0,0.0
9,Southeast Fairbanks,Southeast Fairbanks,Southeast Fairbanks Census Area,"(63.8762, -143.213)",AK,Alaska,0,2240,9,63.8762,-143.2130,6849,831.680649,0.0,0.0,0,0.0
10,Dillingham,Dillingham,Dillingham Census Area,"(59.7991, -158.2351)",AK,Alaska,0,2070,10,59.7991,-158.2351,4899,875.030204,0.0,0.0,0,0.0
12,Kenai Peninsula,Kenai Peninsula,Kenai Peninsula Borough,"(60.2654, -151.5652)",AK,Alaska,0,2122,12,60.2654,-151.5652,58711,914.311389,0.0,0.0,0,0.0
13,Copper River,Copper River,Copper River Census Area,"(61.8834, -143.968)",AK,Alaska,0,2066,13,61.8834,-143.9680,2635,931.017598,0.0,0.0,0,0.0
14,Bristol Bay,Bristol Bay,Bristol Bay Borough,"(58.7439, -156.7)",AK,Alaska,0,2060,14,58.7439,-156.7000,849,958.841172,0.0,0.0,0,0.0
15,Lake and Peninsula,Lake and Peninsula,Lake and Peninsula Borough,"(58.6547, -156.1892)",AK,Alaska,0,2164,15,58.6547,-156.1892,986,969.374718,0.0,0.0,0,0.0
16,Chugach,Chugach,Chugach Census Area,"(60.7228, -145.7754)",AK,Alaska,0,2063,16,60.7228,-145.7754,7015,970.019463,0.0,0.0,0,0.0
17,Kodiak Island,Kodiak Island,Kodiak Island Borough,"(57.6807, -153.7972)",AK,Alaska,0,2150,17,57.6807,-153.7972,13218,1057.624800,0.0,0.0,0,0.0
18,Yakutat,Yakutat,Yakutat City and Borough,"(59.8889, -140.3577)",AK,Alaska,0,2282,18,59.8889,-140.3577,562,1112.409684,0.0,0.0,0,0.0
20,Skagway,Skagway,Skagway Municipality,"(59.563, -135.3363)",AK,Alaska,0,2230,20,59.5630,-135.3363,1329,1224.593408,0.0,0.0,0,0.0
21,Haines,Haines,Haines Borough,"(59.1199, -135.5)",AK,Alaska,0,2100,21,59.1199,-135.5000,2098,1247.303352,0.0,0.0,0,0.0
22,Hoonah-Angoon,Hoonah-Angoon,Hoonah-Angoon Census Area,"(58.2884, -135.643)",AK,Alaska,0,2105,22,58.2884,-135.6430,2327,1293.667849,0.0,0.0,0,0.0
23,Juneau,Juneau,Juneau City and Borough,"(58.4546, -134.1739)",AK,Alaska,0,2110,23,58.4546,-134.1739,32240,1311.605501,0.0,0.0,0,0.0
24,Sitka,Sitka,Sitka City and Borough,"(57.2401, -135.3153)",AK,Alaska,0,2220,24,57.2401,-135.3153,8518,1362.483967,0.0,0.0,0,0.0
25,Petersburg,Petersburg,Petersburg Borough,"(57.1195, -132.9345)",AK,Alaska,0,2195,25,57.1195,-132.9345,3368,1414.381331,0.0,0.0,0,0.0
26,Wrangell,Wrangell,Wrangell City and Borough,"(56.3317, -132.0223)",AK,Alaska,0,2275,26,56.3317,-132.0223,2162,1478.939833,0.0,0.0,0,0.0
27,Prince of Wales-Hyder,Prince of Wales-Hyder,Prince of Wales-Hyder Census Area,"(55.7997, -133.0192)",AK,Alaska,0,2198,27,55.7997,-133.0192,5886,1492.251713,0.0,0.0,0,0.0
28,Ketchikan Gateway,Ketchikan Gateway,Ketchikan Gateway Borough,"(55.5852, -130.9288)",AK,Alaska,0,2130,28,55.5852,-130.9288,13939,1544.783846,0.0,0.0,0,0.0
1392,Kalawao,Kalawao,Kalawao County,"(21.1709, -156.9475)",HI,Hawaii,4,15005,1622,21.1709,-156.9475,48,3527.886266,0.0,0.0,0,0.0

In [70]:
states['percent_dem'] = states['Democrat']/states['total_votes']
states['percent_rep'] = states['Republican']/states['total_votes']
states['dem_lead'] = states['percent_dem']-states['percent_rep']

In [71]:
states.tail()

,County,County Ascii,County Full,Point,State Id,State Name,Cluster,County Fips,F1,Lat,Lng,Population,Starting Dist,Democrat,Republican,Other,total_votes,percent_dem,percent_rep,dem_lead
3138,Putnam,Putnam,Putnam County,"(38.5086, -81.909)",WV,West Virginia,44,54079,1974,38.5086,-81.9090,57385,3626.465952,7878.0,20034.0,589,28501.0,0.276411,0.702923,-0.426511
3139,Raleigh,Raleigh,Raleigh County,"(37.7714, -81.2487)",WV,West Virginia,44,54081,2186,37.7714,-81.2487,74929,3687.312016,7982.0,24673.0,451,33106.0,0.241104,0.745273,-0.504168
3140,Roane,Roane,Roane County,"(38.714, -81.3483)",WV,West Virginia,44,54087,1963,38.7140,-81.3483,14129,3625.335915,1455.0,4213.0,95,5763.0,0.252473,0.731043,-0.478570
3141,Summers,Summers,Summers County,"(37.6559, -80.8586)",WV,West Virginia,44,54089,2235,37.6559,-80.8586,12125,3702.934630,1448.0,4074.0,63,5585.0,0.259266,0.729454,-0.470188
3142,Wyoming,Wyoming,Wyoming County,"(37.6096, -81.5492)",WV,West Virginia,44,54109,2196,37.6096,-81.5492,21581,3691.214551,1157.0,7353.0,82,8592.0,0.134660,0.855796,-0.721136

In [72]:
states.to_csv("county_votes.csv")

In [73]:
states_clustered = states.groupby('Cluster').sum()

In [75]:
states_clustered['percent_dem'] = states_clustered['Democrat']/states_clustered['total_votes']
states_clustered['percent_rep'] = states_clustered['Republican']/states_clustered['total_votes']
states_clustered['dem_lead'] = states_clustered['percent_dem']-states_clustered['percent_rep']

In [79]:
states_clustered = states_clustered.reset_index()
states_clustered.head()

,Cluster,County Fips,F1,Lat,Lng,Population,Starting Dist,Democrat,Republican,Other,total_votes,percent_dem,percent_rep,dem_lead
0,0,751701,863,2380.0943,-5853.7220,4890494,56939.992074,1527509.0,716413.0,72816,2316738.0,0.659336,0.309233,0.350103
1,1,7616884,46721,9857.9467,-22272.3685,4448630,557705.225832,826907.0,1416893.0,67811,2311611.0,0.357719,0.612946,-0.255227
2,2,952858,1258,920.1781,-2449.4791,4669891,46026.300620,1464465.0,978408.0,83038,2525911.0,0.579777,0.387349,0.192428
3,3,1996184,14437,3335.1775,-9266.6061,5319973,201294.849656,1187965.0,1416550.0,80846,2685361.0,0.442386,0.527508,-0.085123
4,4,111455,10240,334.7536,-1520.3970,5236310,34488.893156,1694773.0,689096.0,54755,2438624.0,0.694971,0.282576,0.412395

In [92]:
def vote_share_state(cluster):
    dem_lead = states_clustered.loc[states_clustered['Cluster']==cluster, 'dem_lead'].mode()
    return dem_lead

In [93]:
states['state_vote_share'] = states['Cluster'].apply(lambda x: vote_share_state(x))
states.tail()

,County,County Ascii,County Full,Point,State Id,State Name,Cluster,County Fips,F1,Lat,...,Population,Starting Dist,Democrat,Republican,Other,total_votes,percent_dem,percent_rep,dem_lead,state_vote_share
3138,Putnam,Putnam,Putnam County,"(38.5086, -81.909)",WV,West Virginia,44,54079,1974,38.5086,...,57385,3626.465952,7878.0,20034.0,589,28501.0,0.276411,0.702923,-0.426511,-0.332851
3139,Raleigh,Raleigh,Raleigh County,"(37.7714, -81.2487)",WV,West Virginia,44,54081,2186,37.7714,...,74929,3687.312016,7982.0,24673.0,451,33106.0,0.241104,0.745273,-0.504168,-0.332851
3140,Roane,Roane,Roane County,"(38.714, -81.3483)",WV,West Virginia,44,54087,1963,38.7140,...,14129,3625.335915,1455.0,4213.0,95,5763.0,0.252473,0.731043,-0.478570,-0.332851
3141,Summers,Summers,Summers County,"(37.6559, -80.8586)",WV,West Virginia,44,54089,2235,37.6559,...,12125,3702.934630,1448.0,4074.0,63,5585.0,0.259266,0.729454,-0.470188,-0.332851
3142,Wyoming,Wyoming,Wyoming County,"(37.6096, -81.5492)",WV,West Virginia,44,54109,2196,37.6096,...,21581,3691.214551,1157.0,7353.0,82,8592.0,0.134660,0.855796,-0.721136,-0.332851

In [94]:
states.to_csv("state_votes.csv")

In [98]:
states_clustered['winner'] = states_clustered['dem_lead'].apply(lambda x: "Democrat" if x > 0 else "Republican")

In [100]:
states_clustered.head()

,Cluster,County Fips,F1,Lat,Lng,Population,Starting Dist,Democrat,Republican,Other,total_votes,percent_dem,percent_rep,dem_lead,winner
0,0,751701,863,2380.0943,-5853.7220,4890494,56939.992074,1527509.0,716413.0,72816,2316738.0,0.659336,0.309233,0.350103,Democrat
1,1,7616884,46721,9857.9467,-22272.3685,4448630,557705.225832,826907.0,1416893.0,67811,2311611.0,0.357719,0.612946,-0.255227,Republican
2,2,952858,1258,920.1781,-2449.4791,4669891,46026.300620,1464465.0,978408.0,83038,2525911.0,0.579777,0.387349,0.192428,Democrat
3,3,1996184,14437,3335.1775,-9266.6061,5319973,201294.849656,1187965.0,1416550.0,80846,2685361.0,0.442386,0.527508,-0.085123,Republican
4,4,111455,10240,334.7536,-1520.3970,5236310,34488.893156,1694773.0,689096.0,54755,2438624.0,0.694971,0.282576,0.412395,Democrat

In [101]:
states_clustered['winner'].value_counts()

Democrat      35
Republican    34
Name: winner, dtype: int64

In [102]:
states_clustered.to_csv("states_clustered_votes.csv")